version: '3.3'

services:
  webapp:
    image: clef_webapp
    container_name: clef-webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - './webapp:/usr/src/app'
    ports:
      - 3000:3000
      - 35729:35729
    environment:
      - NODE_ENV=development
      - env_file=./webapp/.env

  core:
    image: clef_core
    container_name: clef-core
    build:
      context: ./core
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - './core/algorithms:/usr/src/algorithms'
      - './symbolic_data:/usr/local/data'
    ports:
      - 8080:8080
    environment:
      - ALGORITHMS_DIR=/usr/src/algorithms
      - DATASETS_DIR=/usr/local/data
      - JARFILE=clef-0.1.jar
      - JAVA_OPTIONS=-Djava.security.egd=file:/dev/./urandom
      - MYSQL_DATABASE=clef
      - MYSQL_ROOT_PASSWORD=root

  db:
    image: clef_db
    container_name: clef-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 3030:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
